# UNet model configuration
model:
  type: "unet"
  
  # Architecture parameters
  in_channels: 1
  out_channels: 1
  features: [64, 128, 256, 512]
  
  # Training parameters
  dropout: 0.0
  batch_norm: true
  
  # Initialization
  weight_init: "kaiming_normal"
  bias_init: "zeros"


